### ISSUE TITLE
A new state object is always returned, even if nothing has changed

### ISSUE THREAD

**Issue by alecmev** [rvikmanis/redux-fp#2]
As per [this line](https://github.com/rvikmanis/redux-fp/blob/e7acea18692024adc5b219d7cd013564177107fd/src/index.js#L103), it appears that a new state object is always returned, even if passed an action type which isn't handled by any updater (or if it is handled, but the same state is returned). This can have a negative effect on performance, since it can trigger unneeded selector calculations and even re-renders, if connected improperly + it renders some tools useless, like [`redux-unhandled-action`](https://github.com/socialtables/redux-unhandled-action).

Do you see this as unwanted behavior, and if so, are you interested in fixing it?

**Comment by rvikmanis** [comment]
It is unclear which function you are referring to, because `concat` returns whatever your updaters return.

**Comment by alecmev** [comment]
Pardon me, this was a hasty conclusion on my part. Was debugging a problem with a Redux middleware, noticed `<...> updaters.reduce` and didn't even read further, assuming that it reduces into a `{}`, but it actually just passes the state around, doesn't even mutate it. The problem is elsewhere.

Closing.
