### ISSUE TITLE
Destructing import fails

### ISSUE THREAD

**Issue by ivanovsaleksejs** [rvikmanis/redux-fp#4]
When trying to import using destructing pattern it fails:

`import { handleAction } from 'redux-fp' // handleAction is undefined`

Can be fixed by using .js version instead of .mjs in package.json.

**Comment by rvikmanis** [comment]
I have no idea what causes this, but if I recall, someone already experienced this with `create-react-app`.

Are you using `create-react-app`? If so, which version?

**Comment by ivanovsaleksejs** [comment]
create-react-app v1.4.1.
